### ISSUE TITLE
Dragons

### ISSUE THREAD

**Issue by Fireflies** [Yumkino/Dragons#1]
I have a phobia of dragons so I'm submitting a DMCA request because I find this disrespectful.

**Comment by Yumkino** [comment]
Please do not leave irrelavent issues.

~closed

**Comment by Fireflies** [comment]
This issue was incredibly relevant. 
Do you have any idea how terrifying dragons can be? 

I demand you re-open it and we have a trial by combat to determine who decides the future of this issue.

**Comment by Fireflies** [comment]
Loser gets fed to a dragon @Yumkino?
